config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks",
                                    registrations: "registrations" }

  resources :users

  resources :albums do
    resources :songs
  end

  resources :playlists do
    member do
      get  "add_song", to: "playlist_songs#new"
      post "add_song", to: "playlist_songs#create"
    end
  end

  root "base#index"
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def index
    @new_albums = Album.order(created_at: :desc).limit(6)
    @albums = Album.all.limit(6)
    @playlists = Playlist.where(user_id: current_user.id).limit(6)
  end

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me, :avatar, :avatar_cache) }
      devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password, :avatar, :avatar_cache, :remove_avatar) }
    end

  private

    def user_not_authorized(exception)
      policy_name = exception.policy.class.to_s.underscore

      flash[:error] = t "#{policy_name}.#{exception.query}", scope: "pundit", default: :default
      redirect_to(request.referrer || root_path)
    end
end

app/helpers/admins/base_helper.rb
module Admins::BaseHelper
end

app/helpers/base_helper.rb
module BaseHelper
end

app/views/base/index.html.slim
.row
  #dot-nav[data-spy="affix"]
    ul
      li.awesome-tooltip.active[title="1"]
        a[href="#home"]
      li.awesome-tooltip[title="2"]
        a[href="#about"]
      li.awesome-tooltip[title="3"]
        a[href="#projects"]
  #main
    section#home
      .container
        h1
          | Fresh albums
          small
            |  newly added albums
        .row-album
          - @new_albums.each do |album|
            -if album.picture.present?
              = link_to image_tag(album.picture.file, class: "img-rounded img-album ", width: "180px"), album_path(album)
    section#about
      .container
        h1
          | My playlists
          small
            |  beloved music here
          = link_to "", new_playlist_path(:playlist), class:"glyphicon glyphicon-plus-sign"
          = link_to "", playlists_path, class:"glyphicon glyphicon-list-alt"
        .row-album
          - @playlists.each do |playlist|
            = link_to image_tag(playlist.picture.file, class: "img-rounded img-album ", width: "180px"), playlist_path(playlist)
    section#projects
      .container
        h1
          | All albums
          small
            |  greatest music
          = link_to "", albums_path, class:"glyphicon glyphicon-folder-open"
        .row-album
          - @albums.each do |album|
            -if album.picture.present?
              = link_to image_tag(album.picture.file, class: "img-rounded img-album ", width: "180px"), album_path(album)