config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks",
                                    registrations: "registrations" }

  resources :users

  resources :albums do
    resources :songs
  end

  resources :playlists do
    member do
      get  "add_song", to: "playlist_songs#new"
      post "add_song", to: "playlist_songs#create"
    end
  end

  root "base#index"
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class Album < ApplicationRecord
  has_many :songs, dependent: :destroy

  belongs_to :user
  has_one :picture, as: :imageable
  accepts_nested_attributes_for :picture

  validates :title, presence: true # move to the form object using ActiveRecord::Model
  validates :picture, presence: true
end

app/controllers/albums_controller.rb
class AlbumsController < BaseController
  before_action :find_user, only: %i[:index]
  before_action :set_album, only: %i[show edit update destroy]

  def index
    @albums = Album.all
  end

  def new
    @album = Album.new
  end

  def show
    @album_songs = @album.songs
    @album_artist = @album_songs.map(&:artist).first
  end

  def create
    @album = Album.new(album_params)
    authorize @album
    if @album.save
      redirect_to album_path(Album.last.id),
      notice: "Album was successfully created."
    else
      render :new
      flash[:error] = @album.errors.full_messages
    end
  end

  def update
    if @album.update(album_params)
      redirect_to @album, notice: "Album was successfully updated."
    else
      render :edit
      flash[:error] = @album.errors.full_messages
    end
  end

  def destroy
    @album.destroy
    redirect_to albums_url, notice: "Album was successfully destroyed."
  end

  private
    def set_album
      @album = Album.find(params[:id])
    end

    def album_params
      params.require(:album).permit(:title, picture_attributes:
      [:id, :imageable_id, :imageable_type, :file, :name])
      .merge(user_id: current_user.id)
    end

    def find_user
      @user = User.find(params[:id])
    end
end

app/views/albums/_form.html.slim
= form_for(@album) do |f|
  = f.label :title
  = f.text_field :title, class: 'form-control'
  = f.fields_for :picture_attributes do |p|
    = p.file_field :file
  .actions
    = f.submit

app/views/albums/edit.html.slim
.container
  h1
    | Edit Album:
    b
      = @album.title
  = simple_form_for @album do |f|
    = f.input :title, class: 'form-control'
    = f.fields_for :picture_attributes do |p|
      = p.file_field :file, class: "form-control"
    br
    br
    .pull-left
      => f.button :submit, class:"btn btn-warning"
      => link_to 'Delete',@album, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger'
    .pull-right
      => link_to 'Back', album_path(@album), class:'btn btn-info'
      => link_to 'My Albums', albums_path, class:'btn btn-primary'
hr
.container
  - @album.songs.each do |s|
    ul.list-group
      li.list-group-item
        b
          = s.title
        span.pull-right
          = link_to '', album_song_path(@album, s), data: { confirm: 'Are you sure?' }, :method => :delete, class:'btn btn-xs btn-warning glyphicon glyphicon-trash'

app/views/albums/index.html.slim
.container
  .row-album
    - @albums.each do |album|
      -if album.picture.present?
        =link_to image_tag(album.picture.file, class: "img-rounded img-album ", width: "140px"), album_path(album)

app/views/albums/new.html.slim
.container
  h1
    | New album
  .row
    .col-md-6.col-md-offset-3
      = simple_form_for @album do |f|
          = f.input :title, class: 'form-control'
          = f.fields_for :picture_attributes do |p|
            = p.file_field :file, class: "form-control"
          br
          .pull-left
            => f.button :submit, class:"btn btn-warning"
            => link_to 'Delete',@album, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger'
          .pull-right
            => link_to 'My Albums', albums_path, class:'btn btn-primary'

app/views/albums/show.html.erb
<div class="container">
<div class="row">
  <div class="col-lg-5">
    <div class="media">
      <a class="pull-left">
      <%= image_tag @album.picture.file, class: "img-thumbnail", width: "100px" %>
      </a>
        <div class="media-body">
          <h4 class="media-heading"><b><%= @album.title %></b></h4>
          <h5><i class="glyphicon glyphicon-user"></i>&nbsp;<%= @album_artist %>&nbsp;•
          <i class="glyphicon glyphicon-music"></i>&nbsp;<%= @album_songs.count %>&nbsp;songs</h5>
          <hr style="margin:10px auto">
        </div>
      <div class="pull-left">
      <%= link_to 'Add song', new_album_song_path(@album, @song), class:'btn btn-success' %>
      <%= link_to 'Edit', edit_album_path(@album), class:'btn btn-warning' %>
      <%= link_to 'Delete',@album, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' %>
      </div>
      <div class="pull-right">
       <%= link_to 'Back', albums_path, class:'btn btn-info' %>
      </div>
    </div>
  </div>
</div>
<br>
<div class="panel panel-default">
  <ul class="list-group", id="playlist">
    <% @album_songs.each do |s| %>
    <li class="list-group-item">
      <a href="<%= s.file.url %>">
      <i class="glyphicon glyphicon-play-circle"></i>
      <%= s.title %>
      </a>
    </li>
    <% end %>
  </ul>
  <div class="panel-footer panel-custom">
    <audio id="audio" preload="auto" tabindex="0" controls="" >
    <source src="">
    </audio>
  </div>
</div>
</div>

app/views/albums/show.html.slim
h1
  | Album
p
  strong
    | Title:
p
  strong
    | Artist:
  = image_tag @album.picture.file, class: "img-thumbnail", width: "100px"
  br
  - @album_songs.each do |s|
    |  <audio id="
    = s.id
    | " controls> <source src="
    = s.file.url
    | ">
    = s.title
br
= link_to 'Add song', new_album_song_path(@album, @song)
br
td
  = link_to 'Listen'
|  |
= link_to 'Edit', edit_album_path(@album)
|  |
= link_to 'Destroy', @album, method: :delete, data: { confirm: 'Are you sure?' }
|  |
= link_to 'Back', albums_path