config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks",
                                    registrations: "registrations" }

  resources :users

  resources :albums do
    resources :songs
  end

  resources :playlists do
    member do
      get  "add_song", to: "playlist_songs#new"
      post "add_song", to: "playlist_songs#create"
    end
  end

  root "base#index"
end

app/models/playlist.rb
# == Schema Information
#
# Table name: playlists
#
#  id         :integer          not null, primary key
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class Playlist < ApplicationRecord
  has_and_belongs_to_many :songs
  has_many :genres, through: :songs
  belongs_to :user
  has_one :picture, as: :imageable
  accepts_nested_attributes_for :picture

  validates :title, presence: true
  validates :picture, presence: true
end

app/controllers/playlists_controller.rb
class PlaylistsController < BaseController
  before_action :find_playlist, only: %i[show edit update destroy]

  def index
    @playlists = current_user.playlists.all
  end

  def new
    @playlist = Playlist.new
  end

  def show
    @songs = @playlist.songs.all
  end

  def create
    @playlist = Playlist.new(playlist_params)
    @playlist.user_id = current_user.id
    if @playlist.save
      redirect_to playlists_path, notice: "Playlist was successfully created."
    else
      render :new
      flash[:error] = @playlist.errors.full_messages.to_sentence.to_s
    end
  end

  def update
    if @playlist.update(playlist_params)
      redirect_to @playlist, notice: "Playlist was successfully updated."
    else
      render :edit
      flash[:error] = @playlist.errors.full_messages.to_sentence.to_s
    end
  end

  def destroy
    # service object
    @playlist.destroy
    redirect_to playlists_url, notice: "Playlist was successfully destroyed."
  end

  private
    def find_playlist
      @playlist = Playlist.find(params[:id])
    end

    def playlist_params
      params.require(:playlist).permit(:title, :user_id, picture_attributes: [:id, :imageable_id, :imageable_type, :file, :name])
    end
end

app/views/playlists/_form.html.slim
= simple_form_for(@playlist) do |f|
  .form-group
    = f.input :title, input_html: { class: 'form-control' }
  
  .form-group
    = f.fields_for :picture_attributes do |p|
      -if @playlist.picture.present?
        =image_tag @playlist.picture.file, class: "img-thumbnail", width: "150px;"
        = p.file_field :file
      -else
        = p.file_field :file
        
  .form-group
    .btn-group role="group" aria-label="actions"
      = f.submit class: "btn btn-primary"
      = link_to 'Back', playlists_path, type: "button", class: "btn btn-success"

app/views/playlists/edit.html.slim
.container
  .row
    .col-md-6.col-md-offset-3
      h2 Edit #{@playlist.title} playlist 
      =render "form"

app/views/playlists/index.html.slim
.row
  .col-md-12
    .pad
      =link_to "Add Playlist", new_playlist_path, type: "button", class: "btn btn-primary"
    - current_user.playlists.each do |playlist|
      .col-sm-6.col-md-4
        .thumbnail
          -if playlist.picture.present?
            =image_tag playlist.picture.file, class: "img-playlist"
          .caption.caption-playlist
            h3= playlist.title
            h5 Tracks:
            
            -if playlist.songs.count >= 5
              -playlist.songs.take(5).each do |song|
                span.glyphicon.glyphicon-music &nbsp;
                =song.title
                br
              span
                strong &#46;&#46;&#46;
            -else
              -playlist.songs.each do |song|
                span.glyphicon.glyphicon-music &nbsp;
                =song.title
                br

          .btn-group role="group" aria-label="action"
            =link_to "Show", playlist, type: "button", class: "btn btn-success"
            =link_to "Edit", edit_playlist_path(playlist), type: "button", class: "btn btn-warning"
            =link_to "Delete", playlist, method: :delete, data: { confirm: "Are you shure?" }, type: "button", class: "btn btn-danger"

app/views/playlists/new.html.slim
.container
  .row
    .col-md-6.col-md-offset-3
      h1 New playlist
      =render "form"

app/views/playlists/show.html.slim
.media
  .media-left
    -if @playlist.picture.present?
      =image_tag @playlist.picture.file, class: "img-thumbnail media-object", width: "200px"
  .media-body
    h2.media-heading=@playlist.title
    hr
    .btn-group role="group" aria-label="action"
      = link_to 'Add songs', add_song_playlist_path(@playlist), type: "button", class: "btn btn-primary"
      = link_to "Back", playlists_path, type: "button", class: "btn btn-success"
br

.panel.panel-default
  ul.list-group id="playlist"
    -@songs.each do |song|
      li.list-group-item
        a href="#{song.file.url}"
          i.glyphicon.glyphicon-play-circle &nbsp;
          =song.title
  .panel-footer.panel-custom
    audio id="audio" preload="auto" tabindex="0" controls=" "
      source src=""