config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks",
                                    registrations: "registrations" }

  resources :users

  resources :albums do
    resources :songs
  end

  resources :playlists do
    member do
      get  "add_song", to: "playlist_songs#new"
      post "add_song", to: "playlist_songs#create"
    end
  end

  root "base#index"
end

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
    div class="alert alert-dismissible alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container-fluid
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Ruby Rouges', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'
      ul.nav.navbar-nav.navbar-right
        -if user_signed_in?
          li
            p.navbar-text
              =link_to current_user.email, user_path(current_user)
          li
              - if policy(:album).create?
                = link_to "Create album", new_album_path(:album)
          li
            =link_to 'Log out', destroy_user_session_path, method: :delete
        -else
          li
            =link_to 'Log in', new_user_session_path
          li
            =link_to 'Sign up', new_user_registration_path

app/views/layouts/_navigation_links.html.slim
- # add navigation links to this file

app/views/layouts/_search.html.slim
= form_tag add_song_playlist_path, method: "get", remote: true, class: "form-inline" do
  .form-group
    = text_field_tag :search, params[:search], class: "form-control"
    = submit_tag "Search Song", class: "btn btn-default"

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Ruby Rogues'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Ruby Rogues'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => 'reload'
    == javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    .container-fluid
      = render 'layouts/messages'
      = yield